// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArmt8-hT9BuJHXj6NYoEl7wqzkVwq1DhI',
    appId: '1:277662804594:web:45194ea7f591a2369a30eb',
    messagingSenderId: '277662804594',
    projectId: 'pawme-81fbe',
    authDomain: 'pawme-81fbe.firebaseapp.com',
    databaseURL: 'https://pawme-81fbe-default-rtdb.firebaseio.com',
    storageBucket: 'pawme-81fbe.firebasestorage.app',
    measurementId: 'G-XHBMNJMBWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBusv_gy6tbQUcyZzyEyFA9tsgAovvbwv4',
    appId: '1:277662804594:android:8d0f584692cd82969a30eb',
    messagingSenderId: '277662804594',
    projectId: 'pawme-81fbe',
    databaseURL: 'https://pawme-81fbe-default-rtdb.firebaseio.com',
    storageBucket: 'pawme-81fbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUIMVCtGzGet0RC6kLa88-yu4IBdG2vHs',
    appId: '1:277662804594:ios:95b479b24f4ad98e9a30eb',
    messagingSenderId: '277662804594',
    projectId: 'pawme-81fbe',
    databaseURL: 'https://pawme-81fbe-default-rtdb.firebaseio.com',
    storageBucket: 'pawme-81fbe.firebasestorage.app',
    iosBundleId: 'com.example.pawme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUIMVCtGzGet0RC6kLa88-yu4IBdG2vHs',
    appId: '1:277662804594:ios:95b479b24f4ad98e9a30eb',
    messagingSenderId: '277662804594',
    projectId: 'pawme-81fbe',
    databaseURL: 'https://pawme-81fbe-default-rtdb.firebaseio.com',
    storageBucket: 'pawme-81fbe.firebasestorage.app',
    iosBundleId: 'com.example.pawme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArmt8-hT9BuJHXj6NYoEl7wqzkVwq1DhI',
    appId: '1:277662804594:web:a817f9c831c905029a30eb',
    messagingSenderId: '277662804594',
    projectId: 'pawme-81fbe',
    authDomain: 'pawme-81fbe.firebaseapp.com',
    databaseURL: 'https://pawme-81fbe-default-rtdb.firebaseio.com',
    storageBucket: 'pawme-81fbe.firebasestorage.app',
    measurementId: 'G-FWBWPMXQ7L',
  );
}
